## Import statements

In [5]:
import pandas as pd

from src.agent.email_agent import EmailAgent
from src.constants import data_path
from src.email_helpers import (
    get_gmail_service,
    export_emails_paginated,
    delete_emails_from_csv,
)
from src.pipeline import classify_csv_in_batches

### Uncomment the cell below to download your emails

In [6]:
# service = get_gmail_service()

# export_emails_paginated(
#     service,
#     query="newer_than:2y",
#     total_limit=10000,
#     page_size=500,
#     resume=True,
# )  # writes to data/emails_review.csv, data/export_checkpoint.json

In [7]:
review_df = pd.read_csv(data_path("emails_review.csv"))
review_df.head()

,message_id,subject,sender,date_sent,important,reason,confidence,needs_review,decision,notes
0,19c654bf930506ca,Your Monday morning order with Uber Eats,Uber Receipts <noreply@uber.com>,"Mon, 16 Feb 2026 07:13:23 +0000 (UTC)",NaN,NaN,NaN,NaN,NaN,NaN
1,19c64e7515ad0656,Security alert,Google <no-reply@accounts.google.com>,"Mon, 16 Feb 2026 05:23:26 GMT",NaN,NaN,NaN,NaN,NaN,NaN
2,19c6223a6c97d3a0,Your Triangle Mastercard eStatement is Ready t...,statements@bank.ctfs.com,"Sun, 15 Feb 2026 16:30:21 +0000 (UTC)",NaN,NaN,NaN,NaN,NaN,NaN
3,19c61fbf49a13704,Treat yourself x 3,DoorDash <no-reply@doordash.com>,"Sun, 15 Feb 2026 15:47:07 +0000 (UTC)",NaN,NaN,NaN,NaN,NaN,NaN
4,19c61740e9568617,"Tamim, don’t miss 50+ top picks up to 50% off. 🚨","""BestBuy.ca"" <newsletter@e.bestbuy.ca>","Sun, 15 Feb 2026 07:18:38 -0600",NaN,NaN,NaN,NaN,NaN,NaN

## Initialize the Agent

In [8]:
# Check which device the LLM will use (cuda = NVIDIA GPU, gpu = Mac Metal, cpu = CPU)
from src.device import print_device_status
print(print_device_status())

LLM device: 'cuda' (NVIDIA GPU). To confirm: run 'nvidia-smi' in another terminal while the model runs; GPU utilization should increase.

In [9]:
agent = EmailAgent()

await classify_csv_in_batches(
    agent,
    batch_size=200,
    resume=True,
    apply_heuristics=True,
    confidence_flag_threshold="Medium",
)  # reads data/emails_review.csv, writes data/classified_emails.csv

c:\Users\Tamim Faruk\Desktop\repos\gmail_scaper\src\pipeline.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'No' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[heuristic_mask, "important"] = "No"
c:\Users\Tamim Faruk\Desktop\repos\gmail_scaper\src\pipeline.py:60: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Heuristic: promotional/newsletter pattern' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[heuristic_mask, "reason"] = "Heuristic: promotional/newsletter pattern"
c:\Users\Tamim Faruk\Desktop\repos\gmail_scaper\src\pipeline.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Medium' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[heuristic_mask, "confidence"] = "Medium"
100%|██████████| 86/86 [02:48<00:00,  1.96s/it]
c:\Users\Tamim Faruk\Desktop\repos\gmail_scaper\src\pipeline.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'No' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[heuristic_mask, "important"] = "No"
c:\Users\Tamim Faruk\Desktop\repos\gmail_scaper\src\pipeline.py:60: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Heuristic: promotional/newsletter pattern' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[heuristic_mask, "reason"] = "Heuristic: promotional/newsletter pattern"
c:\Users\Tamim Faruk\Desktop\repos\gmail_scaper\src\pipeline.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Medium' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[heuristic_mask, "confidence"] = "Medium"
100%|██████████| 98/98 [03:09<00:00,  1.94s/it]
c:\Users\Tamim Faruk\Desktop\repos\gmail_scaper\src\pipeline.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'No' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[heuristic_mask, "important"] = "No"
c:\Users\Tamim Faruk\Desktop\repos\gmail_scaper\src\pipeline.py:60: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Heuristic: promotional/newsletter pattern' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[heuristic_mask, "reason"] = "Heuristic: promotional/newsletter pattern"
c:\Users\Tamim Faruk\Desktop\repos\gmail_scaper\src\pipeline.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Medium' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[heuristic_mask, "confidence"] = "Medium"
100%|██████████| 89/89 [02:44<00:00,  1.85s/it]
c:\Users\Tamim Faruk\Desktop\repos\gmail_scaper\src\pipeline.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'No' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[heuristic_mask, "important"] = "No"
c:\Users\Tamim Faruk\Desktop\repos\gmail_scaper\src\pipeline.py:60: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Heuristic: promotional/newsletter pattern' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[heuristic_mask, "reason"] = "Heuristic: promotional/newsletter pattern"
c:\Users\Tamim Faruk\Desktop\repos\gmail_scaper\src\pipeline.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Medium' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[heuristic_mask, "confidence"] = "Medium"
100%|██████████| 80/80 [02:41<00:00,  2.02s/it]
c:\Users\Tamim Faruk\Desktop\repos\gmail_scaper\src\pipeline.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'No' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[heuristic_mask, "important"] = "No"
c:\Users\Tamim Faruk\Desktop\repos\gmail_scaper\src\pipeline.py:60: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Heuristic: promotional/newsletter pattern' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[heuristic_mask, "reason"] = "Heuristic: promotional/newsletter pattern"
c:\Users\Tamim Faruk\Desktop\repos\gmail_scaper\src\pipeline.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Medium' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[heuristic_mask, "confidence"] = "Medium"
100%|██████████| 83/83 [02:38<00:00,  1.91s/it]

### If you already have classified emails, load them for review

In [10]:
classified_df = pd.read_csv(data_path("classified_emails.csv"))
classified_df.head()

,message_id,subject,sender,date_sent,important,reason,confidence,needs_review,decision,notes
0,19c654bf930506ca,Your Monday morning order with Uber Eats,Uber Receipts <noreply@uber.com>,"Mon, 16 Feb 2026 07:13:23 +0000 (UTC)",Yes,The subject line mentions a specific order wit...,Medium,True,NaN,NaN
1,19c64e7515ad0656,Security alert,Google <no-reply@accounts.google.com>,"Mon, 16 Feb 2026 05:23:26 GMT",Yes,"The subject line ""Security alert"" suggests a p...",High,False,NaN,NaN
2,19c6223a6c97d3a0,Your Triangle Mastercard eStatement is Ready t...,statements@bank.ctfs.com,"Sun, 15 Feb 2026 16:30:21 +0000 (UTC)",NaN,NaN,NaN,True,NaN,NaN
3,19c61fbf49a13704,Treat yourself x 3,DoorDash <no-reply@doordash.com>,"Sun, 15 Feb 2026 15:47:07 +0000 (UTC)",No,The subject line mentions a promotional offer ...,High,False,NaN,NaN
4,19c61740e9568617,"Tamim, don’t miss 50+ top picks up to 50% off. 🚨","""BestBuy.ca"" <newsletter@e.bestbuy.ca>","Sun, 15 Feb 2026 07:18:38 -0600",No,The subject line indicates a promotional offer...,High,False,NaN,NaN

In [11]:
# After reviewing data/classified_emails.csv, set decision=DELETE for emails to trash.
# This cell just reloads the reviewed CSV for deletion.
reviewed_df = pd.read_csv(data_path("classified_emails.csv"))
reviewed_df.head()

,message_id,subject,sender,date_sent,important,reason,confidence,needs_review,decision,notes
0,19c654bf930506ca,Your Monday morning order with Uber Eats,Uber Receipts <noreply@uber.com>,"Mon, 16 Feb 2026 07:13:23 +0000 (UTC)",Yes,The subject line mentions a specific order wit...,Medium,True,NaN,NaN
1,19c64e7515ad0656,Security alert,Google <no-reply@accounts.google.com>,"Mon, 16 Feb 2026 05:23:26 GMT",Yes,"The subject line ""Security alert"" suggests a p...",High,False,NaN,NaN
2,19c6223a6c97d3a0,Your Triangle Mastercard eStatement is Ready t...,statements@bank.ctfs.com,"Sun, 15 Feb 2026 16:30:21 +0000 (UTC)",NaN,NaN,NaN,True,NaN,NaN
3,19c61fbf49a13704,Treat yourself x 3,DoorDash <no-reply@doordash.com>,"Sun, 15 Feb 2026 15:47:07 +0000 (UTC)",No,The subject line mentions a promotional offer ...,High,False,NaN,NaN
4,19c61740e9568617,"Tamim, don’t miss 50+ top picks up to 50% off. 🚨","""BestBuy.ca"" <newsletter@e.bestbuy.ca>","Sun, 15 Feb 2026 07:18:38 -0600",No,The subject line indicates a promotional offer...,High,False,NaN,NaN

In [ ]:
# Preview how many rows are marked for deletion
reviewed_df[reviewed_df["decision"].astype(str).str.upper() == "DELETE"].head()

## Delete the emails

In [ ]:
# Dry run first
delete_emails_from_csv(service, data_path("classified_emails.csv"), dry_run=True)

# Then run for real
# delete_emails_from_csv(service, data_path("classified_emails.csv"), dry_run=False)